# used to build the kernel module
# guided by: http://www.tldp.org/LDP/lkmpg/2.6/html/x181.html
ccflags-y := -std=gnu99 -Wno-declaration-after-statement

obj-m := ccardmodule.o
#ccardmodule-objs := i2c_ccard.o #magnetorquer.o dsa.o i2c_ccard.o






