# used to build the kernel module
# guided by: http://www.tldp.org/LDP/lkmpg/2.6/html/x181.html
ccflags-y := -std=gnu99 -Wno-declaration-after-statement

obj-m := ccardmodule.o
ccardmodule-y := magnetorquer.o dsa.o i2cctl.o






